# NumPy Array'i Olusturmak

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([3.14,4,2,13], dtype ="int")

array([ 3,  4,  2, 13])

In [7]:
#sifirtdan array olusturma

In [8]:
np.zeros(10, dtype =int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [13]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

**sifirdan 31 e kadar 3 er 3 er artacak sekilde dizi olusturabiliyoruz**

In [14]:
np.linspace(0,1,10,)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**iki deger arasinda belirli sayida deger olusturabiliriz "linspace" yazarak.**
**np.full , np.ones , np.arange , gibi hep fonksiyon yaziyoruz**

In [15]:
np.random.normal(10,4, (3,4))


array([[ 8.79116495, 14.84279774, 11.44685836, 13.53119782],
       [14.78007671, 14.12410613, 11.50081379, 18.96185381],
       [10.55689437,  4.50353642,  8.15896557,  5.79066217]])

In [38]:
np.random.randint(0,10,(3,3))

array([[4, 6, 4],
       [0, 8, 3],
       [1, 4, 3]])

# Ozelikleri

* ndim: boyut sayisi
* shape: boyut bilgisi
* size: toplam eleman sayisi
* dtype: array veri tipi    

In [40]:
import numpy as np

In [46]:
np.random.randint(10, size = 10)

array([6, 6, 7, 1, 5, 4, 9, 2, 5, 4])

In [47]:
a = np.random.randint(10, size = 10)

In [48]:
a.ndim

1

In [49]:
a.shape

(10,)

In [50]:
a.size

10

In [51]:
a.dtype

dtype('int32')

In [57]:
b = np.random.randint(10, size = (3,5))

In [55]:
b

array([[3, 2, 1, 7, 2],
       [9, 9, 1, 2, 3],
       [7, 7, 6, 2, 3]])

In [58]:
b.ndim

2

In [59]:
b.size

15

In [60]:
b.shape

(3, 5)

In [61]:
b.dtype

dtype('int32')

# Yeniden Sekillendirme(reshaping)

In [63]:
import numpy as np

In [16]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.arange(1,10)

In [23]:
a.ndim

1

In [24]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
b = a.reshape((1,9))

In [26]:
b.ndim

2

# Array Birlestirmek (Concatenation)

In [75]:
import numpy as np

In [77]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [83]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [84]:
z = np.array([7,8,9])

In [85]:
np.concatenate([x, y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#iki boyut

In [89]:
a = np.array([[1,2,3],
              [4,5,6]])


In [90]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [91]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [92]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayirtma (Splitting)

In [28]:
import numpy as np

In [29]:
x = np.array([1,2,3,99,99,3,2,1])

**0 dan 3 kadar bi bol, daha sonra 5 e kadar**

**ayrica biz burada 3,5 yani iki index verdik 3 islem yapti +1 olarak**

In [30]:
np.split(x,[3,5])


[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [33]:
a,b,c = np.split(x,[3,5])

In [34]:
a

array([1, 2, 3])

In [103]:
b

array([99, 99])

In [105]:
c

array([3, 2, 1])

In [106]:
#iki boyutlu ayirma

In [108]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

**burada ikiye ayriliyor**
**-----ve alt yazarak usttekile uste alttakiler alta gidiyor ve bunu biz atadik**

In [110]:
ust, alt = np.vsplit(m,[2])

In [111]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [113]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [119]:
sag, sol = np.hsplit(m,[2])

In [120]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [121]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Siralama (Sorting)

In [ ]:
import numpy as np

In [122]:
v = np.array([2,1,4,3,5])

In [123]:
v

array([2, 1, 4, 3, 5])

In [125]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [126]:
v

array([2, 1, 4, 3, 5])

In [127]:
v.sort()

In [128]:
v

array([1, 2, 3, 4, 5])

**sort ozelligi daginik sayilari kucukten buyuge siraliyor**

In [129]:
#iki boyutlu array siralama

In [131]:
m = np.random.normal(20,5, (3,3))

In [132]:
m

array([[26.64171448, 19.16194765, 24.12879676],
       [23.0838698 , 10.40255396, 19.18987059],
       [17.51017968, 20.74473506, 13.39936787]])

In [133]:
np.sort(m, axis =1)

array([[19.16194765, 24.12879676, 26.64171448],
       [10.40255396, 19.18987059, 23.0838698 ],
       [13.39936787, 17.51017968, 20.74473506]])

In [134]:
np.sort(m, axis =0)

array([[17.51017968, 10.40255396, 13.39936787],
       [23.0838698 , 19.16194765, 19.18987059],
       [26.64171448, 20.74473506, 24.12879676]])

# Index ile elemanlara Erismek

In [138]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([5, 5, 9, 2, 7, 8, 0, 7, 8, 7])

In [139]:
a[0]

5

In [140]:
a[-2]

8

In [141]:
m = np.random.randint(10, size = (3,5))
m

array([[6, 0, 7, 0, 3],
       [7, 6, 8, 4, 2],
       [9, 3, 8, 2, 3]])

**biz burada random 10' a kadar sayi sec diyoruz, ve bunlari 3 satir 5 sutun olarak yazdiyoruz**

In [142]:
m[0,0]

6

In [143]:
m[1,1]

6

In [146]:
m[1,4]

2

In [147]:
m[1,4] = 99

**burada 1 satir ve 4 sutundaki sayi yerine 99 u ata dedik atama yaptik, 2 yerine 99 yazdi ve random 10 hatasida vermedi cunku biz atadik** 

In [148]:
m

array([[ 6,  0,  7,  0,  3],
       [ 7,  6,  8,  4, 99],
       [ 9,  3,  8,  2,  3]])

In [151]:
m [1,4] = 2.2

In [152]:
m 

array([[6, 0, 7, 0, 3],
       [7, 6, 8, 4, 2],
       [9, 3, 8, 2, 3]])

**kusurati yazinca kusurati yok sayip yani ondalik kabul etmedi normal 2 yazdi**

# slicing ile Elemanlara Erismek (Array Alt Kumesine Erismek)

In [153]:
import numpy as np

In [155]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [156]:
a[0:3]

array([20, 21, 22])

In [157]:
a[:3]

array([20, 21, 22])

In [158]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [159]:
a[1::2]

array([21, 23, 25, 27, 29])

In [160]:
#iki boyutlu slice islemleri


In [164]:
m = np.random.randint(10, size = (5,5))

In [165]:
m

array([[6, 9, 3, 3, 1],
       [4, 4, 0, 1, 1],
       [4, 7, 4, 7, 3],
       [6, 6, 5, 0, 7],
       [7, 5, 2, 0, 5]])

In [166]:
m[:,0]

array([6, 4, 4, 6, 7])

In [168]:
m[:,3]

array([3, 1, 7, 0, 0])

In [169]:
m[0,:]

array([6, 9, 3, 3, 1])

In [170]:
m[0:2, 0:3]

array([[6, 9, 3],
       [4, 4, 0]])

In [171]:
m[:,0:2]

array([[6, 9],
       [4, 4],
       [4, 7],
       [6, 6],
       [7, 5]])

# Alt Kume Uzerindenm Islem Yapmak

In [172]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[5, 6, 9, 4, 8],
       [1, 2, 2, 0, 5],
       [0, 0, 1, 7, 4],
       [3, 3, 1, 7, 8],
       [9, 1, 2, 8, 8]])

In [173]:
alt_a = a[0:3, 0:2]
alt_a

array([[5, 6],
       [1, 2],
       [0, 0]])

**yani burada sutundan 0:3 assagiya 0:2 dize den hepsini aliyorsun bu da alt kume olmus oluyor**

In [180]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [181]:
alt_a

array([[99999,     6],
       [    1,   888],
       [    0,     0]])

In [182]:
a

array([[99999,     6,     9,     4,     8],
       [    1,   888,     2,     0,     5],
       [    0,     0,     1,     7,     4],
       [    3,     3,     1,     7,     8],
       [    9,     1,     2,     8,     8]])

In [183]:
m = np.random.randint(10, size = (5,5))
m

array([[6, 3, 8, 6, 6],
       [8, 0, 0, 0, 3],
       [3, 3, 4, 9, 9],
       [3, 8, 5, 4, 0],
       [0, 6, 2, 4, 9]])

In [186]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[6, 3],
       [8, 0],
       [3, 3]])

In [187]:
alt_b[0,0] = 9999

In [188]:
alt_b

array([[9999,    3],
       [   8,    0],
       [   3,    3]])

In [189]:
m

array([[6, 3, 8, 6, 6],
       [8, 0, 0, 0, 3],
       [3, 3, 4, 9, 9],
       [3, 8, 5, 4, 0],
       [0, 6, 2, 4, 9]])

# Fancy index ile elemanlara Erismek

In [190]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [191]:
v[1]

3

In [192]:
v[4]

12

In [195]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [199]:
al_getir = [1,3,5]

In [200]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [201]:
v[al_getir]

array([ 3,  9, 15])

In [202]:
#iki boyutta fancy


In [211]:
m = np.arange(9).reshape((3,3))

In [212]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [215]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [216]:
m[satir, sutun]

array([1, 5])

In [217]:
#basit index ile fancy index

In [218]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [219]:
m[0, [1,2]]

array([1, 2])

In [223]:
#slice iler fancy

In [222]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Kosullu Eleman Islemleri

In [224]:
import numpy as np
v = np.array([1,2,3,4,5])

In [226]:
v < 3

array([ True,  True, False, False, False])

In [227]:
v[v < 3]

array([1, 2])

In [228]:
v[v > 3]

array([4, 5])

In [229]:
v[v >= 3]

array([3, 4, 5])

In [231]:
v[v <= 3]

array([1, 2, 3])

In [232]:
v[v == 3]

array([3])

In [233]:
v[v != 3] 

array([1, 2, 4, 5])

In [234]:
v*2

array([ 2,  4,  6,  8, 10])

In [235]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [236]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [237]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel islemler

In [238]:
import numpy as np
v = np.array([1,2,3,4,5])

In [239]:
v-1

array([0, 1, 2, 3, 4])

In [240]:
v*5

array([ 5, 10, 15, 20, 25])

In [241]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [242]:
#ufunc

In [243]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

**subtract hepsinden bir cikartiyor**

In [245]:
np.add(v,1)

array([2, 3, 4, 5, 6])

**add hepsine bir ekliyor**

In [247]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

**multiply carpma yapiyor**

In [249]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

**bolme islemi yapiyor**

In [251]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

**iki yilzidz atyarsak karesini 3 yazarsak kupunu aliyoruz**


In [253]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

**power yazarak kuvvetini aliyoruz**

In [255]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

**% bunu yazarak ikiye bolumunden kalanlari getir demis oluyoruz**

In [257]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

**mod % ile yani**

In [261]:
np.absolute(np.array([-3]))

array([3])

**mutlak deger icin absolute kullaniyoruz**

In [262]:
np.sin(360)

0.9589157234143065

In [263]:
np.cos(180)

-0.5984600690578581

In [265]:
v = np.array([1,2,3])

In [267]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [268]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [269]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\onuro\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\onuro\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

# Numpy ile iki Bilinmeyenli Denklem Cozumu

In [1]:
import numpy as np

In [ ]:
5*x0+x1=12
x0+3*x1=10

In [3]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [5]:
a

array([[5, 1],
       [1, 3]])

In [6]:
b

array([12, 10])

In [7]:
x =np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [9]:
array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])

NameError: name 'array' is not defined

In [10]:
array([[0, 1, 2],

             [3, 4, 5],

             [6, 7, 8]])





NameError: name 'array' is not defined